const ORGANIZATION_ENTITY_TYPES = Object.freeze({
    SYSTEM: 'SYSTEM',
    ENVIRONMENT: 'ENVIRONMENT',
    SUB_ENVIRONMENT: 'SUB_ENVIRONMENT',
    ROOM: 'ROOM'
});

const ORGANIZATION_ENTITY_TYPE_VALUES = Object.freeze(Object.values(ORGANIZATION_ENTITY_TYPES));

const ORGANIZATION_LIMITS = Object.freeze({
    KEY_MIN: 2,
    KEY_MAX: 64,
    NAME_MAX: 120,
    DESCRIPTION_MAX: 1_000
});

module.exports = { ORGANIZATION_ENTITY_TYPES, ORGANIZATION_ENTITY_TYPE_VALUES, ORGANIZATION_LIMITS };
