const TICKET_STATUSES = Object.freeze({ OPEN: 'OPEN', CLOSED: 'CLOSED' });
const TICKET_STATUS_VALUES = Object.freeze(Object.values(TICKET_STATUSES));

const TICKET_PRIORITIES = Object.freeze({
    LOW: 'LOW', MEDIUM: 'MEDIUM', HIGH: 'HIGH', CRITICAL: 'CRITICAL'
});
const TICKET_PRIORITY_VALUES = Object.freeze(Object.values(TICKET_PRIORITIES));

const TICKET_VIEWS = Object.freeze({ OPEN: 'OPEN', MY_TASKS: 'MY_TASKS', HISTORY: 'HISTORY' });
const TICKET_VIEW_VALUES = Object.freeze(Object.values(TICKET_VIEWS));

const TICKET_HISTORY_EVENTS = Object.freeze({
    CREATED: 'TICKET_CREATED',
    UPDATED: 'TICKET_UPDATED',
    CLOSED: 'TICKET_CLOSED',
    ASSIGNEES_UPDATED: 'TICKET_ASSIGNEES_UPDATED',
    TRANSFER_INITIATED: 'TICKET_TRANSFER_INITIATED',
    TRANSFER_ACCEPTED: 'TICKET_TRANSFER_ACCEPTED',
    TRANSFER_CANCELLED: 'TICKET_TRANSFER_CANCELLED'
});
const TICKET_HISTORY_EVENT_VALUES = Object.freeze(Object.values(TICKET_HISTORY_EVENTS));

const TICKET_SORT_FIELDS = Object.freeze([
    'createdAt', 'updatedAt', 'closedAt', 'priority', 'ticketNumber', 'sequenceNumber'
]);

const TICKET_MUTABLE_FIELDS = Object.freeze(['subject', 'description', 'priority', 'fieldValues']);

module.exports = { TICKET_STATUSES, TICKET_STATUS_VALUES, TICKET_PRIORITIES, TICKET_PRIORITY_VALUES, TICKET_VIEWS, TICKET_VIEW_VALUES, TICKET_HISTORY_EVENTS, TICKET_HISTORY_EVENT_VALUES, TICKET_SORT_FIELDS, TICKET_MUTABLE_FIELDS };
