const ROLES = Object.freeze({
    SUPER_ADMIN: 'SUPER_ADMIN',
    ENVIRONMENT_ADMIN: 'ENVIRONMENT_ADMIN',
    SYSTEM_ADMIN: 'SYSTEM_ADMIN',
    ROOM_MANAGER: 'ROOM_MANAGER',
    ROOM_USER: 'ROOM_USER'
});

const ROLE_VALUES = Object.freeze(Object.values(ROLES));

const SCOPE_TYPES = Object.freeze({
    SYSTEM: 'SYSTEM',
    ENVIRONMENT: 'ENVIRONMENT',
    SUB_ENVIRONMENT: 'SUB_ENVIRONMENT',
    ROOM: 'ROOM'
});

const SCOPE_TYPE_VALUES = Object.freeze(Object.values(SCOPE_TYPES));

const ROLE_SCOPE_TYPES = Object.freeze({
    [ROLES.SUPER_ADMIN]: SCOPE_TYPES.SYSTEM,
    [ROLES.ENVIRONMENT_ADMIN]: SCOPE_TYPES.ENVIRONMENT,
    [ROLES.SYSTEM_ADMIN]: SCOPE_TYPES.SUB_ENVIRONMENT,
    [ROLES.ROOM_MANAGER]: SCOPE_TYPES.ROOM,
    [ROLES.ROOM_USER]: SCOPE_TYPES.ROOM
});

const REQUESTABLE_ROLES = Object.freeze([
    ROLES.ROOM_USER,
    ROLES.ROOM_MANAGER,
    ROLES.SYSTEM_ADMIN,
    ROLES.ENVIRONMENT_ADMIN
]);

const ACCESS_REQUEST_TYPES = Object.freeze({
    INITIAL_ACCESS: 'INITIAL_ACCESS',
    ADDITIONAL_ACCESS: 'ADDITIONAL_ACCESS'
});

const ACCESS_REQUEST_TYPE_VALUES = Object.freeze(Object.values(ACCESS_REQUEST_TYPES));

const ACCESS_REQUEST_STATUSES = Object.freeze({
    PENDING: 'PENDING',
    APPROVED: 'APPROVED',
    APPROVED_WITH_CHANGES: 'APPROVED_WITH_CHANGES',
    REJECTED: 'REJECTED',
    CANCELLED: 'CANCELLED'
});

const ACCESS_REQUEST_STATUS_VALUES = Object.freeze(Object.values(ACCESS_REQUEST_STATUSES));

const ROLE_AUTHORITY = Object.freeze({
    [ROLES.ROOM_USER]: 1,
    [ROLES.ROOM_MANAGER]: 2,
    [ROLES.SYSTEM_ADMIN]: 3,
    [ROLES.ENVIRONMENT_ADMIN]: 4,
    [ROLES.SUPER_ADMIN]: 5
});

module.exports = {
    ROLES,
    ROLE_VALUES,
    SCOPE_TYPES,
    SCOPE_TYPE_VALUES,
    ROLE_SCOPE_TYPES,
    REQUESTABLE_ROLES,
    ACCESS_REQUEST_TYPES,
    ACCESS_REQUEST_TYPE_VALUES,
    ACCESS_REQUEST_STATUSES,
    ACCESS_REQUEST_STATUS_VALUES,
    ROLE_AUTHORITY
};
