const ASSIGNMENT_SOURCES = Object.freeze({ SINGLE: 'SINGLE', BULK: 'BULK' });
const ASSIGNMENT_SOURCE_VALUES = Object.freeze(Object.values(ASSIGNMENT_SOURCES));

const ASSIGNMENT_END_REASONS = Object.freeze({
    MANUAL_REMOVAL: 'MANUAL_REMOVAL',
    BULK_REMOVAL: 'BULK_REMOVAL',
    REPLACED_ASSIGNMENT_SET: 'REPLACED_ASSIGNMENT_SET',
    TICKET_TRANSFERRED: 'TICKET_TRANSFERRED'
});
const ASSIGNMENT_END_REASON_VALUES = Object.freeze(Object.values(ASSIGNMENT_END_REASONS));

const ASSIGNMENT_HISTORY_VIEWS = Object.freeze({ ACTIVE: 'ACTIVE', HISTORY: 'HISTORY', ALL: 'ALL' });
const ASSIGNMENT_HISTORY_VIEW_VALUES = Object.freeze(Object.values(ASSIGNMENT_HISTORY_VIEWS));

const BULK_ASSIGNMENT_OPERATIONS = Object.freeze({ ADD: 'ADD', REMOVE: 'REMOVE', REPLACE: 'REPLACE' });
const BULK_ASSIGNMENT_OPERATION_VALUES = Object.freeze(Object.values(BULK_ASSIGNMENT_OPERATIONS));

const ASSIGNMENT_LIMITS = Object.freeze({ ASSIGNEES: 50, BULK_TICKETS: 50 });

module.exports = { ASSIGNMENT_SOURCES, ASSIGNMENT_SOURCE_VALUES, ASSIGNMENT_END_REASONS, ASSIGNMENT_END_REASON_VALUES, ASSIGNMENT_HISTORY_VIEWS, ASSIGNMENT_HISTORY_VIEW_VALUES, BULK_ASSIGNMENT_OPERATIONS, BULK_ASSIGNMENT_OPERATION_VALUES, ASSIGNMENT_LIMITS };
